# Project: Project1
# Makefile created by Dev-C++ 5.11

CPP      = g++.exe
CC       = gcc.exe
WINDRES  = windres.exe
OBJ      = mainGetset.o
LINKOBJ  = mainGetset.o
LIBS     = -L"E:/Developer/DevC++/Dev-Cpp/MinGW64/lib" -L"E:/Developer/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/lib" -static-libgcc
INCS     = -I"E:/Developer/DevC++/Dev-Cpp/MinGW64/include" -I"E:/Developer/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Developer/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include"
CXXINCS  = -I"E:/Developer/DevC++/Dev-Cpp/MinGW64/include" -I"E:/Developer/DevC++/Dev-Cpp/MinGW64/x86_64-w64-mingw32/include" -I"E:/Developer/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include" -I"E:/Developer/DevC++/Dev-Cpp/MinGW64/lib/gcc/x86_64-w64-mingw32/4.9.2/include/c++"
BIN      = 3.exe
CXXFLAGS = $(CXXINCS) 
CFLAGS   = $(INCS) 
RM       = rm.exe -f

.PHONY: all all-before all-after clean clean-custom

all: all-before $(BIN) all-after

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CPP) $(LINKOBJ) -o $(BIN) $(LIBS)

mainGetset.o: mainGetset.cpp
	$(CPP) -c mainGetset.cpp -o mainGetset.o $(CXXFLAGS)
